### ISSUE TITLE
data1D.load fails to detect header rows

### ISSUE THREAD

**Issue by igresh** [refnx/refnx#236]
[c_PLP0033831.txt](https://github.com/refnx/refnx/files/2613507/c_PLP0033831.txt)

The Try/Except process designed to count the number of header rows is doing so by catching ValueErrors, when the enclosed operation is throwing ParseErrors.

Could just allow the user to supply the number of headers rows as a kwarg?

**Comment by andyfaff** [comment]
ok, I didn't see the file in the comment as I was reading on my phone. I'll look into it.

**Comment by andyfaff** [comment]
I try that file on my computer, and it works without issue. The bit of code that determines how many header rows there could be could probably be improved, but that will require a regex wizard.
`ReflectDataset` is passing the load up to the base class to read, because it's not an XML file. It's that baseclass load that's the issue. I'm not sure why you see it and I don't.
What version of numpy are you using?

**Comment by igresh** [comment]
numpy 1.14.1.

Could be some sort of Mac/PC file handling issue?

**Comment by arm61** [comment]
Maybe end of line vs. carriage return bug related to how the different OSs are parsing the file?

**Comment by andyfaff** [comment]
Hopefully closed by #237. If it's not, then please reopen.
