### ISSUE TITLE
pip install refnx leads to error with missing "_open_mp_helpers"

### ISSUE THREAD

**Issue by franzlang** [refnx/refnx#381]
When trying to install the latest version of this package via pip leads to the installation being aborted with the error message 
setup.py line7: ModuleNotFoundError: No module named '_open_mp_helpers'
Checking setup.py in the tarball for version 0.1.9 (the newest one on PyPi) indeed shows that it tries to import _open_mp_helpers, but that module is not included in the tarball.
The next older version (0.1.8) can be installed via pip successfully.

**Comment by andyfaff** [comment]
@franzlang thanks for contributing. What platform are you on? Is a wheel available for your platform, or are you trying to install from source?
I noticed this and have tried to fix this in 99cfe8c, which will be in the next release.

**Comment by andyfaff** [comment]
Installation on macOS (Python 3.7) using `pip install --no-cache-dir refnx` works without issue. However, there is a wheel available for that target. So wheel installation seems to work, so I'm guessing that the fail is when there is no wheel available and the install is from sdist. The sdist tarball for 0.1.8 does not contain the `_open_mp_helpers` file, but the next release will.

@franzlang, sorry that you're experiencing issues. You'll be able to install 0.1.10dev if you download the source from github. Otherwise you'll have to wait for the next release.

**Comment by andyfaff** [comment]
Installation and test run from sdist is now being tested in the travisCI tests.
