### ISSUE TITLE
curvefitter.fit does not accept kwargs for ‘L-BFGS-B’

### ISSUE THREAD

**Issue by jfkcooper** [refnx/refnx#421]
fitter = CurveFitter(objective, nwalkers=600)
fitter.fit(method=‘L-BFGS-B’,target='nll',######)

I expected (possibly incorrectly), that any args from https://docs.scipy.org/doc/scipy/reference/optimize.minimize-lbfgsb.html#optimize-minimize-lbfgsb should be accepted when put where ###### is. Instead get an error that it is unexpected.

**Comment by andyfaff** [comment]
If `minimizer in {'shgo', 'differential_evolution', 'dual_annealing'}` then you pass the keywords as they would be passed to `scipy.optimize.differential_evolution`: `fitter.fit('differential_evolution', seed=1)`. The same happens if you use `least_squares`.

If you choose a minimizer option that comes via `scipy.optimize.minimize` then you also do the same thing, `fitter.fit('L-BFGS-B', callback=c)`. However, [note that `callback` is a keyword for the `minimize` function](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize). If you want to use a minimizer specific keyword then you would need to do the following:
```
# maxiter is not a keyword for minimize, but it is for L-BFGS-B
# options keyword is known by minimize
fitter.fit('L-BFGS-B', options={'maxiter':2})
```

**Comment by jfkcooper** [comment]
Thanks! the options={} was what I needed
